export type Product = Readonly<{
  id: string;
  slug: string;
  sku: string;
  name: string;
  subtitle: string;
  description: string;
  price: number;
  compareAtPrice?: number;
  image: string;
  gallery: readonly string[];
  category: "Bó hoa" | "Giỏ hoa" | "Hoa cưới" | "Hoa sự kiện";
  occasions: readonly string[];
  flowers: readonly string[];
  palette: string;
  seasonal: string;
  stock: number;
  featured?: boolean;
  badge?: string;
}>;

export const products: readonly Product[] = [
  {
    id: "amour-bleu",
    slug: "amour-bleu",
    sku: "TF-BQ-001",
    name: "Tình Xanh",
    subtitle: "Cẩm tú cầu xanh và hồng garden",
    description: "Bó hoa chủ đạo xanh sương, điểm hồng phấn và trắng kem. Một thiết kế dịu dàng nhưng có chiều sâu cho sinh nhật, kỷ niệm và lời cảm ơn trang trọng.",
    price: 890_000,
    compareAtPrice: 990_000,
    image: "/products/amour-bleu.png",
    gallery: ["/products/amour-bleu.png", "/products/pastel-poetry.png", "/products/blue-sonata.png"],
    category: "Bó hoa",
    occasions: ["Sinh nhật", "Kỷ niệm", "Cảm ơn"],
    flowers: ["Cẩm tú cầu", "Hồng garden", "Cát tường"],
    palette: "Xanh - hồng",
    seasonal: "Quanh năm, thay hoa tương đương theo mùa",
    stock: 12,
    featured: true,
    badge: "Bán chạy",
  },
  {
    id: "pastel-poetry",
    slug: "pastel-poetry",
    sku: "TF-BQ-002",
    name: "Vần Thơ Màu Phấn",
    subtitle: "Hoa theo mùa sắc pastel",
    description: "Một bản phối nhiều tầng giữa hồng phấn, kem đào, tím lilac và xanh nhạt, được gói thủ công bằng giấy mỹ thuật cao cấp.",
    price: 790_000,
    image: "/products/pastel-poetry.png",
    gallery: ["/products/pastel-poetry.png", "/products/amour-bleu.png", "/products/romance-deep.png"],
    category: "Bó hoa",
    occasions: ["Sinh nhật", "Chúc mừng", "Tặng người thương"],
    flowers: ["Hồng", "Cẩm chướng", "Lan", "Cát tường"],
    palette: "Pastel",
    seasonal: "Xuân - Hè",
    stock: 9,
    featured: true,
    badge: "Theo mùa",
  },
  {
    id: "morning-mist",
    slug: "morning-mist",
    sku: "TF-BQ-003",
    name: "Sương Mai",
    subtitle: "Cẩm tú cầu và cát tường tinh khôi",
    description: "Thiết kế thoáng, tự nhiên với sắc xanh dịu và nhịp hoa trắng thanh lịch, phù hợp tặng đồng nghiệp hoặc trang trí bàn tiệc.",
    price: 690_000,
    image: "/products/morning-mist.png",
    gallery: ["/products/morning-mist.png", "/products/blue-sonata.png", "/products/pastel-poetry.png"],
    category: "Bó hoa",
    occasions: ["Cảm ơn", "Chúc mừng", "Khai trương"],
    flowers: ["Cẩm tú cầu", "Cát tường", "Bạch đàn"],
    palette: "Xanh - trắng",
    seasonal: "Hè - Thu",
    stock: 8,
    featured: true,
  },
  {
    id: "garden-whisper",
    slug: "garden-whisper",
    sku: "TF-BQ-004",
    name: "Lời Thì Thầm Của Vườn",
    subtitle: "Hồng garden và thanh liễu",
    description: "Bó hoa lãng mạn lấy cảm hứng từ vườn hoa sớm mai, cân bằng giữa những nụ hồng mềm và cành lá mảnh.",
    price: 590_000,
    image: "/products/garden-whisper.png",
    gallery: ["/products/garden-whisper.png", "/products/pastel-poetry.png", "/products/romance-deep.png"],
    category: "Bó hoa",
    occasions: ["Hẹn hò", "Sinh nhật", "Xin lỗi"],
    flowers: ["Hồng garden", "Thanh liễu", "Cẩm chướng"],
    palette: "Hồng - tím",
    seasonal: "Quanh năm",
    stock: 16,
    badge: "Mới",
  },
  {
    id: "spring-lullaby",
    slug: "spring-lullaby",
    sku: "TF-BQ-005",
    name: "Khúc Ru Mùa Xuân",
    subtitle: "Tulip và lily vàng hồng",
    description: "Tulip vàng tươi kết hợp lily hồng mềm mại tạo nên một món quà rạng rỡ, giàu năng lượng nhưng vẫn nữ tính.",
    price: 750_000,
    image: "/products/spring-lullaby.png",
    gallery: ["/products/spring-lullaby.png", "/products/sunlit-joy.png", "/products/morning-mist.png"],
    category: "Bó hoa",
    occasions: ["Sinh nhật", "Chúc mừng", "Tân gia"],
    flowers: ["Tulip", "Lily"],
    palette: "Vàng - hồng",
    seasonal: "Xuân",
    stock: 6,
    badge: "Giới hạn",
  },
  {
    id: "blue-sonata",
    slug: "blue-sonata",
    sku: "TF-GH-006",
    name: "Khúc Xanh",
    subtitle: "Giỏ cẩm tú cầu xanh thanh lịch",
    description: "Giỏ hoa bàn với những khối cẩm tú cầu xanh đầy đặn, xen cúc kem và lá bạc, dành cho không gian tiếp khách sang trọng.",
    price: 1_090_000,
    image: "/products/blue-sonata.png",
    gallery: ["/products/blue-sonata.png", "/products/amour-bleu.png", "/products/morning-mist.png"],
    category: "Giỏ hoa",
    occasions: ["Kỷ niệm", "Khai trương", "Tân gia"],
    flowers: ["Cẩm tú cầu", "Cúc mẫu đơn", "Hồng"],
    palette: "Xanh - kem",
    seasonal: "Hè - Thu",
    stock: 5,
    featured: true,
    badge: "Cao cấp",
  },
  {
    id: "romance-deep",
    slug: "romance-deep",
    sku: "TF-BQ-007",
    name: "Tình Nồng",
    subtitle: "Hồng đỏ nghệ thuật",
    description: "Hồng đỏ và vàng champagne trong lớp gói tối màu, một lựa chọn giàu cảm xúc cho ngày kỷ niệm và lời tỏ tình.",
    price: 820_000,
    image: "/products/romance-deep.png",
    gallery: ["/products/romance-deep.png", "/products/garden-whisper.png", "/products/amour-bleu.png"],
    category: "Bó hoa",
    occasions: ["Tỏ tình", "Kỷ niệm", "Valentine"],
    flowers: ["Hồng đỏ", "Hồng vàng"],
    palette: "Đỏ - vàng",
    seasonal: "Quanh năm",
    stock: 11,
  },
  {
    id: "sunlit-joy",
    slug: "sunlit-joy",
    sku: "TF-BQ-008",
    name: "Nắng Vui",
    subtitle: "Hướng dương và hoa đồng nội",
    description: "Một bó hoa vui tươi với hướng dương làm tâm điểm, điểm hoa trắng và lá xanh, thích hợp cho lễ tốt nghiệp và khởi đầu mới.",
    price: 490_000,
    image: "/products/sunlit-joy.png",
    gallery: ["/products/sunlit-joy.png", "/products/spring-lullaby.png", "/products/morning-mist.png"],
    category: "Bó hoa",
    occasions: ["Tốt nghiệp", "Chúc mừng", "Sinh nhật"],
    flowers: ["Hướng dương", "Cúc tana", "Lá bạc"],
    palette: "Vàng - xanh",
    seasonal: "Hè",
    stock: 18,
  },
  {
    id: "me-oi",
    slug: "me-oi",
    sku: "TF-BQ-009",
    name: "Mẹ Ơi",
    subtitle: "Cẩm chướng hồng kết tròn",
    description: "Cẩm chướng hồng kết thành bó tròn, chen thanh liễu và lá bạc cho dáng hoa mềm hơn. Một bó vừa tay để tặng mẹ ngày lễ hoặc mang theo trong buổi ghé nhà.",
    price: 650_000,
    image: "/products/me-oi.webp",
    gallery: ["/products/me-oi.webp"],
    category: "Bó hoa",
    occasions: ["Ngày của Mẹ", "8/3", "20/10"],
    flowers: ["Cẩm chướng hồng", "Thanh liễu", "Lá bạc"],
    palette: "Hồng phấn - kem",
    seasonal: "Quanh năm",
    stock: 12,
    badge: "Tặng mẹ",
  },
  {
    id: "ghe-tham",
    slug: "ghe-tham",
    sku: "TF-BQ-010",
    name: "Ghé Thăm",
    subtitle: "Đồng tiền cam và cát tường trắng",
    description: "Đồng tiền cam, cát tường trắng và cúc tana được gói thoáng, vừa tay mang vào phòng bệnh. Màu sáng, dáng gọn và không quá phô trương.",
    price: 590_000,
    image: "/products/ghe-tham.webp",
    gallery: ["/products/ghe-tham.webp"],
    category: "Bó hoa",
    occasions: ["Thăm bệnh", "Chúc mau khỏe"],
    flowers: ["Đồng tiền cam", "Cát tường trắng", "Cúc tana"],
    palette: "Cam - vàng - trắng",
    seasonal: "Quanh năm",
    stock: 10,
  },
  {
    id: "bui-phan",
    slug: "bui-phan",
    sku: "TF-BQ-011",
    name: "Bụi Phấn",
    subtitle: "Freesia trắng và phi yến tím",
    description: "Freesia trắng đi cùng phi yến tím và thạch thảo, kết theo dáng dài thanh thoát. Mẫu hoa lịch sự để gửi thầy cô mà vẫn có nét riêng.",
    price: 720_000,
    image: "/products/bui-phan.webp",
    gallery: ["/products/bui-phan.webp"],
    category: "Bó hoa",
    occasions: ["Ngày Nhà giáo", "Cảm ơn thầy cô"],
    flowers: ["Freesia trắng", "Phi yến tím", "Thạch thảo"],
    palette: "Trắng - tím",
    seasonal: "Thu - Xuân, thay hoa tương đương khi hết mùa",
    stock: 8,
    badge: "20/11",
  },
  {
    id: "loi-hen-do",
    slug: "loi-hen-do",
    sku: "TF-BQ-012",
    name: "Lời Hẹn Đỏ",
    subtitle: "Hồng đỏ kết xoắn gọn",
    description: "Mười tám bông hồng đỏ được kết sát tay, giữ dáng tròn gọn và bọc giấy màu trầm. Hợp cho một lời tỏ tình rõ ràng, không cần thêm nhiều lời.",
    price: 1_190_000,
    image: "/products/loi-hen-do.webp",
    gallery: ["/products/loi-hen-do.webp"],
    category: "Bó hoa",
    occasions: ["Valentine", "Tỏ tình", "Cầu hôn"],
    flowers: ["Hồng Ecuador đỏ", "Lá bạc"],
    palette: "Đỏ rượu - xanh bạc",
    seasonal: "Quanh năm, đặt trước 24 giờ",
    stock: 6,
    badge: "Đặt trước",
  },
  {
    id: "nha-co-em",
    slug: "nha-co-em",
    sku: "TF-GH-013",
    name: "Nhà Có Em",
    subtitle: "Giỏ cúc ping pong dịu sáng",
    description: "Cúc ping pong, cát tường và cẩm chướng chùm cắm trong giỏ thấp, dễ đặt ở bàn khách. Mẫu không dùng lily, hợp mang đến chúc mừng gia đình vừa đón em bé.",
    price: 790_000,
    image: "/products/nha-co-em.webp",
    gallery: ["/products/nha-co-em.webp"],
    category: "Giỏ hoa",
    occasions: ["Mừng em bé", "Đầy tháng"],
    flowers: ["Cúc ping pong trắng", "Cát tường kem", "Cẩm chướng chùm"],
    palette: "Kem - xanh mint - đào nhạt",
    seasonal: "Quanh năm",
    stock: 7,
    badge: "Mẫu mới",
  },
  {
    id: "hien-nha-moi",
    slug: "hien-nha-moi",
    sku: "TF-GH-014",
    name: "Hiên Nhà Mới",
    subtitle: "Thiên điểu và hồng môn dáng cao",
    description: "Thiên điểu và hồng môn được cắm lệch một phía, phần lá mở rộng để giỏ hoa nhìn thoáng. Dáng cao hợp đặt ở sảnh hoặc góc phòng khách mới.",
    price: 990_000,
    image: "/products/hien-nha-moi.webp",
    gallery: ["/products/hien-nha-moi.webp"],
    category: "Giỏ hoa",
    occasions: ["Tân gia", "Chuyển nhà"],
    flowers: ["Thiên điểu", "Hồng môn cam", "Monstera"],
    palette: "Cam - xanh lá",
    seasonal: "Quanh năm",
    stock: 5,
  },
  {
    id: "loc-xuan",
    slug: "loc-xuan",
    sku: "TF-GH-015",
    name: "Lộc Xuân",
    subtitle: "Địa lan vàng và nụ tầm xuân",
    description: "Địa lan vàng làm mảng chính, điểm cúc tròn và vài nhánh tầm xuân đỏ. Giỏ hoa có dáng gọn để đặt trên bàn tiếp khách những ngày đầu năm.",
    price: 1_290_000,
    image: "/products/loc-xuan.webp",
    gallery: ["/products/loc-xuan.webp"],
    category: "Giỏ hoa",
    occasions: ["Tết", "Chúc năm mới"],
    flowers: ["Địa lan vàng", "Cúc ping pong vàng", "Nụ tầm xuân"],
    palette: "Vàng - đỏ - xanh",
    seasonal: "Mùa Tết, đặt trước 2 ngày",
    stock: 4,
    badge: "Theo mùa",
  },
  {
    id: "ngay-chung-doi",
    slug: "ngay-chung-doi",
    sku: "TF-HC-016",
    name: "Ngày Chung Đôi",
    subtitle: "Rum trắng cầm tay dáng dài",
    description: "Rum trắng giữ nguyên thân dài, bó gọn cùng baby và lá olive. Kiểu ôm tay hợp váy cưới tối giản và những buổi lễ có không gian nhỏ.",
    price: 950_000,
    image: "/products/ngay-chung-doi.webp",
    gallery: ["/products/ngay-chung-doi.webp"],
    category: "Hoa cưới",
    occasions: ["Lễ cưới", "Lễ gia tiên"],
    flowers: ["Hoa rum trắng", "Baby trắng", "Lá olive"],
    palette: "Trắng - xanh olive",
    seasonal: "Quanh năm, đặt trước 3 ngày",
    stock: 4,
    badge: "Hoa cưới",
  },
  {
    id: "sanh-buoc",
    slug: "sanh-buoc",
    sku: "TF-HC-017",
    name: "Sánh Bước",
    subtitle: "Thược dược đỏ rượu dáng bán nguyệt",
    description: "Thược dược đỏ rượu làm tâm, hồng chùm đi thấp và dương xỉ mở sang hai bên. Dáng bán nguyệt lên ảnh rõ nhưng vẫn dễ cầm.",
    price: 1_090_000,
    image: "/products/sanh-buoc.webp",
    gallery: ["/products/sanh-buoc.webp"],
    category: "Hoa cưới",
    occasions: ["Lễ đính hôn", "Chụp ảnh cưới"],
    flowers: ["Thược dược đỏ rượu", "Hồng chùm", "Lá dương xỉ"],
    palette: "Đỏ rượu - hồng bụi",
    seasonal: "Thu - Đông, thay thược dược tương đương khi hết mùa",
    stock: 3,
  },
  {
    id: "mo-loi",
    slug: "mo-loi",
    sku: "TF-SK-018",
    name: "Mở Lối",
    subtitle: "Kệ lan mokara hai tầng",
    description: "Kệ hai tầng với lan mokara chạy thành mảng, hồng môn tạo điểm đỏ và lá lớn giữ phom. Dáng kệ cao, dễ nhìn khi đặt trước cửa hàng.",
    price: 1_850_000,
    image: "/products/mo-loi.webp",
    gallery: ["/products/mo-loi.webp"],
    category: "Hoa sự kiện",
    occasions: ["Khai trương", "Khánh thành"],
    flowers: ["Lan mokara cam", "Hồng môn đỏ", "Monstera"],
    palette: "Cam - đỏ - xanh",
    seasonal: "Quanh năm, đặt trước 1 ngày",
    stock: 3,
    badge: "Khai trương",
  },
  {
    id: "mot-loi-tien",
    slug: "mot-loi-tien",
    sku: "TF-SK-019",
    name: "Một Lời Tiễn",
    subtitle: "Kệ hoa trắng dáng oval",
    description: "Ly và cúc trắng được cắm thành một mảng oval gọn, viền lá xanh vừa đủ. Thiết kế giữ màu sắc trang nhã cho lời chia buồn.",
    price: 1_450_000,
    image: "/products/mot-loi-tien.webp",
    gallery: ["/products/mot-loi-tien.webp"],
    category: "Hoa sự kiện",
    occasions: ["Chia buồn", "Tưởng niệm"],
    flowers: ["Ly trắng", "Cúc trắng", "Lá cau"],
    palette: "Trắng - xanh",
    seasonal: "Quanh năm",
    stock: 3,
  },
  {
    id: "ban-tiec-chom-thu",
    slug: "ban-tiec-chom-thu",
    sku: "TF-SK-020",
    name: "Bàn Tiệc Chớm Thu",
    subtitle: "Hồng môn nâu cam cắm thấp",
    description: "Hồng môn nâu cam và scabiosa được cắm thấp, mở ngang theo dáng lưỡi liềm. Bình không che tầm nhìn nên hợp đặt giữa bàn tiệc hoặc bàn gallery.",
    price: 890_000,
    image: "/products/ban-tiec-chom-thu.webp",
    gallery: ["/products/ban-tiec-chom-thu.webp"],
    category: "Hoa sự kiện",
    occasions: ["Tiệc doanh nghiệp", "Bàn gallery", "Tiệc tối"],
    flowers: ["Hồng môn nâu cam", "Scabiosa tím", "Lá bạc"],
    palette: "Đất nung - tím - xanh khói",
    seasonal: "Hè - Thu, thay hoa tương đương theo mùa",
    stock: 8,
  },
];

export const categories = ["Tất cả", "Bó hoa", "Giỏ hoa", "Hoa cưới", "Hoa sự kiện"] as const;

export function getProduct(slug: string) {
  return products.find((product) => product.slug === slug);
}

export function getFeaturedProducts() {
  return products.filter((product) => product.featured);
}
