export type Product = Readonly<{
  id: string;
  slug: string;
  sku: string;
  name: string;
  subtitle: string;
  description: string;
  price: number;
  compareAtPrice?: number;
  image: string;
  gallery: readonly string[];
  category: "Bó hoa" | "Giỏ hoa" | "Hoa cưới" | "Hoa sự kiện";
  occasions: readonly string[];
  flowers: readonly string[];
  palette: string;
  seasonal: string;
  stock: number;
  featured?: boolean;
  badge?: string;
}>;

export const products: readonly Product[] = [
  {
    id: "vuon-trong-nang",
    slug: "vuon-trong-nang",
    sku: "TF-BQ-001",
    name: "Vườn Trong Nắng",
    subtitle: "Sắc hoa ấm áp cho một ngày thật trong trẻo",
    description: "Thiết kế dáng tròn với những mảng màu sáng và lớp lá xanh tự nhiên, mang cảm giác như một khu vườn nhỏ vừa đón nắng đầu ngày.",
    price: 690_000,
    image: "/products/vuon-trong-nang.webp",
    gallery: ["/products/vuon-trong-nang.webp"],
    category: "Bó hoa",
    occasions: ["Sinh nhật", "Chúc mừng", "Cảm ơn"],
    flowers: ["Hồng cam", "Hồng vàng", "Cúc", "Hoa đồng nội theo mùa"],
    palette: "Vàng nắng - hồng phấn - xanh lá",
    seasonal: "Quanh năm, phối hoa tương đương theo mùa",
    stock: 14,
    featured: true,
    badge: "Mới",
  },
  {
    id: "nang-goi-niem-vui",
    slug: "nang-goi-niem-vui",
    sku: "TF-BQ-002",
    name: "Nắng Gọi Niềm Vui",
    subtitle: "Một khoảng nắng vui được gói trao tận tay",
    description: "Bó hoa có phom mở thoáng, phối sắc vàng tươi cùng các gam sáng dịu để gửi lời chúc tích cực trong sinh nhật hoặc một khởi đầu mới.",
    price: 790_000,
    image: "/products/nang-goi-niem-vui.webp",
    gallery: ["/products/nang-goi-niem-vui.webp"],
    category: "Bó hoa",
    occasions: ["Sinh nhật", "Tốt nghiệp", "Khởi đầu mới"],
    flowers: ["Hướng dương", "Hồng", "Đồng tiền", "Cúc ping pong", "Baby"],
    palette: "Vàng tươi - kem - xanh non",
    seasonal: "Quanh năm, phối hoa tương đương theo mùa",
    stock: 12,
    featured: true,
    badge: "Bán chạy",
  },
  {
    id: "hen-nhau-mua-hong",
    slug: "hen-nhau-mua-hong",
    sku: "TF-BQ-003",
    name: "Hẹn Nhau Mùa Hồng",
    subtitle: "Bó hoa tông hồng cho những cuộc hẹn dịu dàng",
    description: "Các lớp hoa hồng sắc được kết mềm và ôm tròn trong giấy gói thanh lịch, phù hợp để đánh dấu một cuộc hẹn, ngày kỷ niệm hoặc lời tỏ tình.",
    price: 1_190_000,
    image: "/products/hen-nhau-mua-hong.webp",
    gallery: ["/products/hen-nhau-mua-hong.webp"],
    category: "Bó hoa",
    occasions: ["Hẹn hò", "Kỷ niệm", "Tỏ tình"],
    flowers: ["Lily hồng", "Hồng", "Hồng chùm", "Cúc tana"],
    palette: "Hồng phấn - hồng đậm - kem",
    seasonal: "Quanh năm, phối hoa tương đương theo mùa",
    stock: 7,
    featured: true,
    badge: "Cao cấp",
  },
  {
    id: "dao-choi-trong-vuon",
    slug: "dao-choi-trong-vuon",
    sku: "TF-BQ-004",
    name: "Dạo Chơi Trong Vườn",
    subtitle: "Phom hoa tự nhiên như vừa hái từ khu vườn nhỏ",
    description: "Bó hoa phối kiểu vườn với độ cao thấp tự nhiên và những khoảng thở mềm mại, tạo cảm giác gần gũi cho sinh nhật, lời cảm ơn hoặc một buổi ghé thăm.",
    price: 620_000,
    image: "/products/dao-choi-trong-vuon.webp",
    gallery: ["/products/dao-choi-trong-vuon.webp"],
    category: "Bó hoa",
    occasions: ["Sinh nhật", "Cảm ơn", "Ghé thăm"],
    flowers: ["Hồng", "Sao nhái", "Phi yến xanh", "Cúc nhí"],
    palette: "Hồng đào - tím nhạt - xanh lá",
    seasonal: "Quanh năm, phối hoa tương đương theo mùa",
    stock: 16,
    featured: true,
    badge: "Mẫu mới",
  },
  {
    id: "chuong-trang-binh-yen",
    slug: "chuong-trang-binh-yen",
    sku: "TF-BQ-005",
    name: "Chuông Trắng Bình Yên",
    subtitle: "Sắc trắng nhẹ nhàng cho những phút giây an yên",
    description: "Thiết kế tông trắng kem có phom gọn và nhịp hoa thanh thoát, dành cho lời hỏi thăm chân thành, món quà tân gia hoặc một lời cảm ơn trang nhã.",
    price: 590_000,
    image: "/products/chuong-trang-binh-yen.webp",
    gallery: ["/products/chuong-trang-binh-yen.webp"],
    category: "Bó hoa",
    occasions: ["Cảm ơn", "Thăm hỏi", "Tân gia"],
    flowers: ["Hoa chuông trắng", "Sao xanh", "Lá phụ"],
    palette: "Trắng - kem - xanh dịu",
    seasonal: "Quanh năm, phối hoa tương đương theo mùa",
    stock: 10,
    badge: "Thanh lịch",
  },
  {
    id: "trang-xanh",
    slug: "trang-xanh",
    sku: "TF-BQ-006",
    name: "Trăng Xanh",
    subtitle: "Bó hoa xanh lam dịu như ánh trăng đầu tối",
    description: "Sắc xanh lam chuyển nhẹ sang trắng và tím nhạt trong một phom hoa cân đối, tạo món quà có nét riêng cho sinh nhật, kỷ niệm và người thương.",
    price: 720_000,
    image: "/products/trang-xanh.webp",
    gallery: ["/products/trang-xanh.webp"],
    category: "Bó hoa",
    occasions: ["Sinh nhật", "Kỷ niệm", "Tặng người thương"],
    flowers: ["Hoa trắng nhiều lớp", "Hoa điểm xanh", "Lá phụ"],
    palette: "Xanh lam - trắng - tím nhạt",
    seasonal: "Quanh năm, phối hoa tương đương theo mùa",
    stock: 9,
    featured: true,
    badge: "Được yêu thích",
  },
  {
    id: "vuon-co-tich",
    slug: "vuon-co-tich",
    sku: "TF-GH-007",
    name: "Vườn Cổ Tích",
    subtitle: "Giỏ hoa nhiều tầng sắc như một khu vườn cổ tích",
    description: "Giỏ hoa được cắm nhiều tầng với các cụm màu đan xen và phần lá mở thoáng, tạo điểm nhấn nổi bật cho sinh nhật, tân gia hoặc dịp chúc mừng.",
    price: 1_350_000,
    image: "/products/vuon-co-tich.webp",
    gallery: ["/products/vuon-co-tich.webp"],
    category: "Giỏ hoa",
    occasions: ["Sinh nhật", "Tân gia", "Chúc mừng"],
    flowers: ["Cẩm tú cầu", "Hồng", "Cúc tana", "Lan vàng"],
    palette: "Hồng - tím - xanh - kem",
    seasonal: "Quanh năm, phối hoa tương đương theo mùa",
    stock: 5,
    featured: true,
    badge: "Giỏ hoa cao cấp",
  },
  {
    id: "cham-may",
    slug: "cham-may",
    sku: "TF-HC-008",
    name: "Chạm Mây",
    subtitle: "Hoa cầm tay mềm nhẹ cho ngày chung đôi",
    description: "Bó hoa cưới tông trắng kem có đường nét mềm, vừa tay cầm và dễ hòa cùng nhiều kiểu váy, dành cho lễ cưới, lễ gia tiên hoặc buổi chụp ảnh.",
    price: 1_150_000,
    image: "/products/cham-may.webp",
    gallery: ["/products/cham-may.webp"],
    category: "Hoa cưới",
    occasions: ["Lễ cưới", "Lễ gia tiên", "Chụp ảnh cưới"],
    flowers: ["Cẩm tú cầu xanh", "Hồng kem", "Cẩm chướng hồng", "Hoa hồng nhạt theo mùa"],
    palette: "Trắng mây - kem - xanh nhạt",
    seasonal: "Quanh năm, đặt trước 3 ngày để chọn hoa phù hợp",
    stock: 4,
    featured: true,
    badge: "Hoa cưới",
  },
  {
    id: "tu-cau-be-xinh",
    slug: "tu-cau-be-xinh",
    sku: "TF-BQ-009",
    name: "Tú Cầu Bé Xinh",
    subtitle: "Bó hoa nhỏ xinh với sắc xanh trong trẻo",
    description: "Thiết kế cỡ nhỏ được gói gọn gàng, phối sắc xanh ngọc cùng các điểm sáng mềm mại để dễ trao trong sinh nhật, lời cảm ơn hoặc buổi ghé thăm.",
    price: 490_000,
    image: "/products/tu-cau-be-xinh.webp",
    gallery: ["/products/tu-cau-be-xinh.webp"],
    category: "Bó hoa",
    occasions: ["Sinh nhật", "Cảm ơn", "Ghé thăm"],
    flowers: ["Cẩm tú cầu xanh", "Hoa trắng theo mùa"],
    palette: "Xanh ngọc - trắng - kem",
    seasonal: "Quanh năm, phối hoa tương đương theo mùa",
    stock: 13,
    badge: "Dễ thương",
  },
  {
    id: "sac-mau-le-hoi",
    slug: "sac-mau-le-hoi",
    sku: "TF-BQ-010",
    name: "Sắc Màu Lễ Hội",
    subtitle: "Bó hoa rộn ràng với những mảng màu tươi sáng",
    description: "Nhiều gam màu được sắp thành từng lớp có nhịp điệu, tạo một bó hoa vui mắt và tràn năng lượng cho dịp chúc mừng, tốt nghiệp hoặc sinh nhật.",
    price: 980_000,
    image: "/products/sac-mau-le-hoi.webp",
    gallery: ["/products/sac-mau-le-hoi.webp"],
    category: "Bó hoa",
    occasions: ["Chúc mừng", "Tốt nghiệp", "Sinh nhật"],
    flowers: ["Hồng", "Cúc", "Lan", "Hoa đồng nội theo mùa"],
    palette: "Cam - hồng - vàng - tím",
    seasonal: "Quanh năm, phối hoa tương đương theo mùa",
    stock: 8,
    badge: "Rực rỡ",
  },
  {
    id: "sanh-doi-hong-lam",
    slug: "sanh-doi-hong-lam",
    sku: "TF-HC-011",
    name: "Sánh Đôi Hồng Lam",
    subtitle: "Hoa cầm tay hòa sắc hồng và lam cho lễ cưới",
    description: "Bó hoa cưới phối hai tông hồng lam trong phom cầm tay cân đối, lên ảnh rõ màu nhưng vẫn mềm mại cho lễ cưới, lễ đính hôn hoặc buổi chụp hình.",
    price: 1_250_000,
    image: "/products/sanh-doi-hong-lam.webp",
    gallery: ["/products/sanh-doi-hong-lam.webp"],
    category: "Hoa cưới",
    occasions: ["Lễ cưới", "Lễ đính hôn", "Chụp ảnh cưới"],
    flowers: ["Hồng", "Cẩm tú cầu xanh", "Alstroemeria", "Sao xanh"],
    palette: "Hồng bụi - lam nhạt - trắng",
    seasonal: "Quanh năm, đặt trước 3 ngày để chọn hoa phù hợp",
    stock: 4,
    featured: true,
    badge: "Hoa cưới",
  },
  {
    id: "may-lam",
    slug: "may-lam",
    sku: "TF-BQ-012",
    name: "Mây Lam",
    subtitle: "Bó hoa tông lam mềm mại như một áng mây",
    description: "Sắc lam khói được làm dịu bằng những điểm hoa trắng và lớp gói sáng, tạo món quà nhẹ nhàng cho sinh nhật, lời cảm ơn hoặc người thương.",
    price: 650_000,
    image: "/products/may-lam.webp",
    gallery: ["/products/may-lam.webp"],
    category: "Bó hoa",
    occasions: ["Sinh nhật", "Cảm ơn", "Tặng người thương"],
    flowers: ["Phi yến xanh", "Phi yến trắng"],
    palette: "Lam khói - trắng - xanh bạc",
    seasonal: "Quanh năm, phối hoa tương đương theo mùa",
    stock: 11,
    badge: "Dịu dàng",
  },
];

export const categories = ["Tất cả", "Bó hoa", "Giỏ hoa", "Hoa cưới"] as const;

export function getProduct(slug: string) {
  return products.find((product) => product.slug === slug);
}

export function getFeaturedProducts() {
  return products.filter((product) => product.featured);
}
